#Requires -Version 7.4
<#
    D008: the status lines in README.md and docs/FINDINGS.md are written by scripts/Update-Status.ps1
    from one run of scripts/verify.ps1, and each byte pin verify.ps1 retires names a decision that exists.

    These tests do not rerun the suite. That is verify.ps1's job, and a test that ran the suite would
    be counted inside the suite it ran. What they hold is the shape the generator writes into and the
    link from each retirement to its decision, so that neither one can quietly go missing.
#>

BeforeAll {
    $script:RepoRoot = Split-Path $PSScriptRoot -Parent
    $script:Begin = '<!-- status:begin -- generated by scripts/Update-Status.ps1 from one run of scripts/verify.ps1 -Json; do not edit by hand -->'
    $script:End   = '<!-- status:end -->'

    function script:Get-Block {
        param([string]$RelPath)
        $text = [System.IO.File]::ReadAllText((Join-Path $script:RepoRoot $RelPath))
        $b = $text.IndexOf($script:Begin, [System.StringComparison]::Ordinal)
        $e = $text.IndexOf($script:End, [System.StringComparison]::Ordinal)
        [pscustomobject]@{
            Begins = ([regex]::Matches($text, [regex]::Escape($script:Begin))).Count
            Ends   = ([regex]::Matches($text, [regex]::Escape($script:End))).Count
            Body   = if ($b -ge 0 -and $e -gt $b) { $text.Substring($b, $e - $b) } else { '' }
        }
    }
}

Describe 'The generated status blocks' {
    # Markers only. What goes between them is the generator's output, and asserting its numbers here
    # would make the suite fail on the very block the generator needs a green suite to write.
    # verify.ps1 already holds the README table to a live run.
    It '<_> holds the status markers exactly once, begin before end' -ForEach @('README.md', 'docs/FINDINGS.md') {
        $block = Get-Block -RelPath $_
        $block.Begins | Should -Be 1
        $block.Ends   | Should -Be 1
        $block.Body   | Should -Not -BeNullOrEmpty
    }
}

Describe 'Every byte pin verify.ps1 retires names a decision that exists' {
    It 'each RetiredBy in scripts/verify.ps1 is a ## heading in docs/DECISIONS.md' {
        $verify    = [System.IO.File]::ReadAllText((Join-Path $script:RepoRoot 'scripts/verify.ps1'))
        $decisions = [System.IO.File]::ReadAllText((Join-Path $script:RepoRoot 'docs/DECISIONS.md'))
        $retired   = @([regex]::Matches($verify, "RetiredBy = '(D\d{3})'") | ForEach-Object { $_.Groups[1].Value })
        $retired | Should -Be @('D002', 'D008')
        foreach ($d in $retired) { $decisions | Should -Match ('(?m)^## {0} ' -f $d) }
    }
}
