#Requires -Version 7.4
<#
.SYNOPSIS
    Regenerates the status blocks in README.md and docs/FINDINGS.md from one run of scripts/verify.ps1.

.DESCRIPTION
    The status lines are measurements. Typed by hand, they rotted twice (README.md, "rotted twice").
    This script runs `scripts/verify.ps1 -Json`, which runs the suite and scripts/Measure-Modules.ps1,
    and rewrites the text between the status markers in both files from that run's JSON. Nothing
    outside the markers is touched.

    It refuses a dirty tree, except for the two files it writes. "Measured at <sha>" is only true if
    the code at <sha> is the code that ran.

    verify.ps1 checks README.md's module table against the live run. So when the table was stale,
    the first run fails that one line. The block is written, and verify.ps1 runs a second time,
    and the second run is the one recorded. Any other failed line stops this script, and nothing
    is written: a red verify is reported, not published as status.

.EXAMPLE
    pwsh -NoProfile -File scripts/Update-Status.ps1
#>
[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
$PSNativeCommandUseErrorActionPreference = $true
Set-StrictMode -Version 3.0

$RepoRoot = Split-Path $PSScriptRoot -Parent
$Targets  = @('README.md', 'docs/FINDINGS.md')
$Begin    = '<!-- status:begin -- generated by scripts/Update-Status.ps1 from one run of scripts/verify.ps1 -Json; do not edit by hand -->'
$End      = '<!-- status:end -->'
$ReadmeTableLine = 'README per-module counts match a live run'

$dirty = @(& git -C $RepoRoot status --porcelain | ForEach-Object { $_.Substring(3) } | Where-Object { $Targets -notcontains $_ })
if ($dirty.Count) { throw "update-status: the tree is dirty outside $($Targets -join ', '): $($dirty -join ', ')" }

function Invoke-Verify {
    $scratch = Join-Path ([System.IO.Path]::GetTempPath()) ("core-verify-{0}.json" -f $PID)
    $PSNativeCommandUseErrorActionPreference = $false
    & pwsh -NoProfile -File (Join-Path $RepoRoot 'scripts/verify.ps1') -Json $scratch | Out-Host
    $exit = $LASTEXITCODE
    if (-not (Test-Path -LiteralPath $scratch)) { throw "update-status: verify.ps1 exited $exit and wrote no JSON" }
    $run = Get-Content -LiteralPath $scratch -Raw | ConvertFrom-Json -Depth 10
    Remove-Item -LiteralPath $scratch -Force
    return [pscustomobject]@{ Exit = $exit; Run = $run }
}

function Get-StatusLines {
    param($Run)
    $m = $Run.measured
    $skips = @($Run.lines | Where-Object Verdict -eq 'SKIP' | ForEach-Object { '`' + ($_.Detail -split '\s+')[0] + '`' })
    $skipText = if ($skips.Count) { " -- $($skips -join ', ') (DECISIONS D008)" } else { '' }
    return @(
        "Measured at ``$($Run.head.Substring(0, 7))``:"
        ''
        "- ``scripts/verify.ps1``: **$($Run.checks) checks, $($Run.passed) passed, $($Run.failed) failed, $($Run.skipped) skipped**$skipText."
        "- ``scripts/Measure-Modules.ps1``: **$($m.total) tests, $($m.passed) passed, $($m.failed) failed, $($m.skipped) skipped, $($m.exceptions) exceptions**."
    )
}

function Get-ModuleTable {
    param($Run)
    $byName = @{}
    foreach ($row in $Run.measured.byModule) { $byName[$row.Name] = [int]$row.Total }
    $lines = @('| Module | Import path | Suite | Tests |', '|---|---|---|---|')
    foreach ($name in @('ledger', 'policy', 'plans')) {
        $lines += "| ``$name`` | ``modules/$name/$name.psd1`` | ``modules/$name/tests/`` | **$($byName[$name])** |"
    }
    $lines += "| — | the repository's own suite | ``tests/`` | **$($byName['repo'])** |"
    $lines += "| | | **total** | **$($Run.measured.total)** |"
    return $lines
}

function Set-Block {
    param([string]$RelPath, [string[]]$Body)
    $path = Join-Path $RepoRoot $RelPath
    $text = [System.IO.File]::ReadAllText($path)
    $b = $text.IndexOf($Begin, [System.StringComparison]::Ordinal)
    $e = $text.IndexOf($End, [System.StringComparison]::Ordinal)
    if ($b -lt 0 -or $e -lt $b -or $text.IndexOf($Begin, $b + 1, [System.StringComparison]::Ordinal) -ge 0) {
        throw "update-status: $RelPath must hold the status markers exactly once, begin before end"
    }
    $new = $text.Substring(0, $b) + (@($Begin) + $Body + @($End) -join "`n") + $text.Substring($e + $End.Length)
    [System.IO.File]::WriteAllText($path, $new, [System.Text.UTF8Encoding]::new($false))
}

function Write-Status {
    param($Run)
    $lines = Get-StatusLines -Run $Run
    Set-Block -RelPath 'README.md' -Body ($lines + @('') + (Get-ModuleTable -Run $Run))
    Set-Block -RelPath 'docs/FINDINGS.md' -Body $lines
}

$v = Invoke-Verify
$failedNames = @($v.Run.lines | Where-Object Verdict -eq 'FAIL' | ForEach-Object Name)
if ($failedNames.Count -eq 1 -and $failedNames[0] -eq $ReadmeTableLine) {
    Write-Host 'update-status: only the README table was stale; writing it and verifying again'
    Write-Status -Run $v.Run
    $v = Invoke-Verify
    $failedNames = @($v.Run.lines | Where-Object Verdict -eq 'FAIL' | ForEach-Object Name)
}
if ($v.Exit -ne 0 -or $failedNames.Count) {
    throw "update-status: verify.ps1 exited $($v.Exit), failed: $($failedNames -join '; '). Nothing further written."
}

Write-Status -Run $v.Run
Write-Host "update-status: wrote $($Targets -join ', ') from verify.ps1 at $($v.Run.head)"
